rule_files:
  - terraform/projects/app-ecs-services/config/alerts/observe-alerts.yml

evaluation_interval: 1m

tests:
    - interval: 30s
      input_series:
          - series: 'prometheus_build_info{job="prometheus",version="2.4.2"}'
            values: '1+0x14' # 1 1 1 1 1 1 1 1 1 1 1 1 1 1

          - series: 'up{job="alertmanager", instance="localhost:9090"}'
            values: '0+0x14' 
          - series: 'up{job="prometheus", instance="localhost:9090"}'
            values: '0+0x14' 
          - series: 'up{instance="app:0",job="test",org="test",space="prod"}'
            values: '0+0x2880' # running for 24 hours, 30s interval: 2 x 60 x 24 = 2880

          - series: 'prometheus_sd_file_mtime_seconds{filename="/target-1.json",instance="prom-1",job="prometheus"}'
            values: '_x14'  # no metrics provided, could just leave this metric out
          - series: 'prometheus_engine_query_duration_seconds_sum{instance="prom-1",job="prometheus",slice="inner_eval"}'
            values: '100+288x2880'
          - series: 'prometheus_engine_query_duration_seconds_sum{instance="prom-1",job="prometheus",slice="prepare_time"}'
            values: '5+0.1x240'
          - series: 'prometheus_engine_query_duration_seconds_sum{instance="prom-1",job="prometheus",slice="queue_time"}'
            values: '0.1+0.01x240'
          - series: 'prometheus_engine_query_duration_seconds_sum{instance="prom-1",job="prometheus",slice="result_sort"}'
            values: '0.002+0.001x240'

      alert_rule_test:
          - eval_time: 5m
            alertname: RE_Observe_AlertManager_Below_Threshold
            exp_alerts:
                - exp_labels:
                      severity: page
                      instance: localhost:9090
                      job: alertmanager
                      product: prometheus
                  exp_annotations:
                      summary: "Service is below the expected instance Threshold"
                      description: "The service name is alertmanager. The URL experiencing the issue is localhost:9090."
                      runbook: "https://re-team-manual.cloudapps.digital/observe-support.html#re-observe-alertmanager-below-threshold"

          - eval_time: 5m
            alertname: RE_Observe_Prometheus_Below_Threshold
            exp_alerts:
                - exp_labels:
                      severity: page
                      instance: localhost:9090
                      job: prometheus
                      product: prometheus
                  exp_annotations:
                      summary: "Service is below the expected instance Threshold"
                      description: "The service name is prometheus. The URL experiencing the issue is localhost:9090."
                      runbook: "https://re-team-manual.cloudapps.digital/observe-support.html#re-observe-prometheus-below-threshold"

          - eval_time: 5m
            alertname: RE_Observe_No_FileSd_Targets
            exp_alerts:
                - exp_labels:
                      severity: page
                      product: prometheus
                  exp_annotations:
                      summary: "No file_sd targets detected"
                      description: "No file_sd targets were detected.  Is there a problem accessing the targets bucket?"
                      runbook: "https://re-team-manual.cloudapps.digital/observe-support.html#re-observe-no-filesd-targets"

          - eval_time: 5m
            alertname: RE_Observe_Prometheus_Over_Capacity
            exp_alerts:
                - exp_labels:
                      severity: page
                      instance: prom-1
                      job: prometheus
                      product: prometheus
                  exp_annotations:
                      summary: "Service is over capacity."
                      description: "The service name is prometheus. The URL experiencing the issue is prom-1."
                      runbook: "https://re-team-manual.cloudapps.digital/observe-support.html#re-observe-prometheus-over-capacity"

          - eval_time: 2h
            alertname: RE_Observe_Prometheus_High_Load
            exp_alerts:
                - exp_labels:
                      severity: ticket
                      instance: prom-1
                      job: prometheus
                      product: prometheus
                  exp_annotations:
                      summary: "Service is approaching capacity."
                      description: "The service name is prometheus. The URL experiencing the issue is prom-1."
                      runbook: "https://re-team-manual.cloudapps.digital/observe-support.html#re-observe-prometheus-high-load"

          - eval_time: 24h
            alertname: RE_Observe_Target_Down
            exp_alerts:
                - exp_labels:
                      severity: ticket
                      instance: app:0
                      job: test
                      org: test
                      product: prometheus
                      space: prod
                  exp_annotations:
                      summary: "test target is down"
                      description: "One of the test targets has been down for 24 hours"
                      runbook: "https://re-team-manual.cloudapps.digital/observe-support.html#re-observe-target-down"

      promql_expr_test:
          - expr: (count(prometheus_sd_file_mtime_seconds) or count(up)*0) < 1
            eval_time: 5m
            exp_samples:
                - labels: '{}'
                  value: 0
          - expr: sum without(slice)(rate(prometheus_engine_query_duration_seconds_sum{job="prometheus"}[5m])) > 8
            eval_time: 5m
            exp_samples:
                - labels: '{instance="prom-1",job="prometheus"}'
                  value: 9.6037E+00
          - expr: sum without(slice)(rate(prometheus_engine_query_duration_seconds_sum{job="prometheus"}[2h])) > 4
            eval_time: 2h
            exp_samples:
                - labels: '{instance="prom-1",job="prometheus"}'
                  value: 9.6037E+00
          - expr: up{} == 0
            eval_time: 24h
            exp_samples:
                - labels: '{__name__="up", instance="app:0", job="test", org="test", space="prod"}'
                  value: 0
