rule_files:
  - terraform/projects/app-ecs-services/config/alerts/<alerts yml file>

evaluation_interval: 1m

tests:
    - interval: 30s
      input_series:
          - series: 'up{instance="app:0",job="test",org="YourTeam",space="prod"}'
            values: '0+0x10' # running for 5 minutes, 30s interval: 2 x 5 = 10

      alert_rule_test:
          - eval_time: 5m
            alertname: YourTeam_alert
            exp_alerts:
                - exp_labels:
                      severity: ticket
                      instance: app:0
                      job: test
                      org: YourTeam
                      space: prod
                      product: YourTeam
                  exp_annotations:
                      summary: "Summary matching the alert summary"
                      description: "Description matching the alert description"
                      runbook: "https://runbook.com/link-to-your-runbook#alert"

      promql_expr_test:
          - expr: up{} == 0
            eval_time: 24h
            exp_samples:
                - labels: '{__name__="up", instance="app:0", job="test", org="YourTeam", space="prod"}'
                  value: 0
